services:

  php:
    build:  ./docker/php
    volumes:
      - .:/www

  web:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/www/public
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
      - '80:80'

  db:
    image: mariadb:10.5.26
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
