controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

back:
    resource:
        path: ../src/Controller/Back/
        namespace: App\Controller\Back
    type: attribute
    prefix: /admin
